# Generated by Django 4.0.3 on 2022-04-26 11:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
