# Generated by Django 4.0.3 on 2022-04-27 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0003_issue_fine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fine',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LibraryApp.usermember'),
        ),
    ]
